import type { ParsedFile } from "../parser.js";
import type { FileSummary, SymbolSummary } from "../summarizer.js";

/**
 * Builds a `## <filePath>` section for tree-structure.md.
 *
 * Format:
 * ```
 * ## src/auth/jwt.ts
 * - `signToken(payload, secret)` — Signs a JWT with HS256; returns a signed token string
 * - `verifyToken(token, secret)` — Verifies token signature and expiry
 * ```
 */
export function renderFileSection(
  parsed: ParsedFile,
  summary: FileSummary
): string {
  if (parsed.symbols.length === 0) return "";

  const summaryMap = new Map<string, string>(
    summary.symbols.map((s: SymbolSummary) => [s.name, s.summary])
  );

  const lines: string[] = [`## ${parsed.filePath}`];

  for (const sym of parsed.symbols) {
    const sig = sym.params !== undefined ? `\`${sym.name}(${sym.params})\`` : `\`${sym.name}\``;
    const desc = summaryMap.get(sym.name);
    lines.push(desc ? `- ${sig} — ${desc}` : `- ${sig}`);
  }

  return lines.join("\n");
}

/**
 * Renders the full tree-structure.md from an array of parsed files + summaries.
 */
// No truncation here — the file on disk is the complete index.
// The slicer caps what gets sent to the LLM per task.
export function renderFullTree(
  files: Array<{ parsed: ParsedFile; summary: FileSummary }>
): string {
  const header = "# Tree Structure\n\n> Auto-generated by `crix init`.\n";
  const sections: string[] = [];

  for (const { parsed, summary } of files) {
    const section = renderFileSection(parsed, summary);
    if (section) sections.push(section);
  }

  return header + "\n" + sections.join("\n\n");
}
