import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { truncateToLimit } from "@crix/shared";
import {
  getCodePracticesPath,
  getContextMdPath,
  getCrixDir,
  getProjectMdPath,
  getTreeStructurePath,
} from "@crix/core";
import type { ContextLimits } from "@crix/shared";

const DEFAULT_PROJECT_MD = `# Project

> Fill in your project overview, goals, and tech stack here.
`;

const DEFAULT_CONTEXT_MD = `# Context

> Current working context — updated automatically after each completed task.
`;

const DEFAULT_CODE_PRACTICES_MD = `# Code Practices

> Coding standards, naming conventions, and patterns for this project.
`;

const DEFAULT_TREE_STRUCTURE_MD = `# Tree Structure

> Auto-generated by \`crix init\`. Run \`crix init\` to populate this file.
`;

function ensureDir(filePath: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function read(filePath: string, defaultContent: string): string {
  if (!existsSync(filePath)) return defaultContent;
  return readFileSync(filePath, "utf8");
}

function write(filePath: string, content: string): void {
  ensureDir(filePath);
  writeFileSync(filePath, content, "utf8");
}

export function initContextFiles(projectPath: string): void {
  const dir = getCrixDir(projectPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const files: Array<[string, string]> = [
    [getProjectMdPath(projectPath), DEFAULT_PROJECT_MD],
    [getContextMdPath(projectPath), DEFAULT_CONTEXT_MD],
    [getCodePracticesPath(projectPath), DEFAULT_CODE_PRACTICES_MD],
    [getTreeStructurePath(projectPath), DEFAULT_TREE_STRUCTURE_MD],
  ];

  for (const [filePath, defaultContent] of files) {
    if (!existsSync(filePath)) write(filePath, defaultContent);
  }
}

export function readProjectMd(projectPath: string): string {
  return read(getProjectMdPath(projectPath), DEFAULT_PROJECT_MD);
}

export function writeProjectMd(projectPath: string, content: string, limits: ContextLimits): void {
  write(getProjectMdPath(projectPath), truncateToLimit(content, limits.projectMd));
}

export function readContextMd(projectPath: string): string {
  return read(getContextMdPath(projectPath), DEFAULT_CONTEXT_MD);
}

export function writeContextMd(projectPath: string, content: string, limits: ContextLimits): void {
  write(getContextMdPath(projectPath), truncateToLimit(content, limits.contextMd));
}

export function readCodePractices(projectPath: string): string {
  return read(getCodePracticesPath(projectPath), DEFAULT_CODE_PRACTICES_MD);
}

export function writeCodePractices(projectPath: string, content: string, limits: ContextLimits): void {
  write(getCodePracticesPath(projectPath), truncateToLimit(content, limits.codePractices));
}

export function readTreeStructure(projectPath: string): string {
  return read(getTreeStructurePath(projectPath), DEFAULT_TREE_STRUCTURE_MD);
}

export function writeTreeStructure(projectPath: string, content: string, limits: ContextLimits): void {
  write(getTreeStructurePath(projectPath), truncateToLimit(content, limits.treeStructure));
}
